REWARD_WHITE = -0.04
REWARD_GREEN = 1.0
REWARD_BROWN = -1.0
REWARD_WALL = 0.0

INTENDED_PROBABILITY = 0.8
LEFT_PROBABILITY = 0.1
RIGHT_PROBABILITY = 0.1

DISCOUNT_FACTOR = 0.99

MAX_REWARD = 1.0

MAX_ALLOWED_ERROR = 30

MAX_DISCOUNTED_ERROR = MAX_ALLOWED_ERROR * MAX_REWARD

# Number of time Bellman algo is worked out
K = 20

UTILITY_UPPER_BOUND = MAX_REWARD / (1 - DISCOUNT_FACTOR)